// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmCecvEhU5Q2SaLzngnAM6AX9qeNOJE98',
    appId: '1:825282016133:web:2c3d64ddf1024ddadc8aec',
    messagingSenderId: '825282016133',
    projectId: 'praynotify',
    authDomain: 'praynotify.firebaseapp.com',
    databaseURL: 'https://praynotify-default-rtdb.firebaseio.com',
    storageBucket: 'praynotify.firebasestorage.app',
    measurementId: 'G-DKLRSZDEEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCht957PUihw9JHQ14ssvKFwHi1EYQC8cM',
    appId: '1:825282016133:android:9acb1931374ef415dc8aec',
    messagingSenderId: '825282016133',
    projectId: 'praynotify',
    databaseURL: 'https://praynotify-default-rtdb.firebaseio.com',
    storageBucket: 'praynotify.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjampACOhvSUygPUZuX8X-_aLn2D-8Mc4',
    appId: '1:825282016133:ios:3de7c5729d839f35dc8aec',
    messagingSenderId: '825282016133',
    projectId: 'praynotify',
    databaseURL: 'https://praynotify-default-rtdb.firebaseio.com',
    storageBucket: 'praynotify.firebasestorage.app',
    iosBundleId: 'com.example.sadaqaSite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjampACOhvSUygPUZuX8X-_aLn2D-8Mc4',
    appId: '1:825282016133:ios:3de7c5729d839f35dc8aec',
    messagingSenderId: '825282016133',
    projectId: 'praynotify',
    databaseURL: 'https://praynotify-default-rtdb.firebaseio.com',
    storageBucket: 'praynotify.firebasestorage.app',
    iosBundleId: 'com.example.sadaqaSite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyy67a6IwcJQr1dUD1dpb5GCEcFFCorio',
    appId: '1:825282016133:web:2fc76e125637b82fdc8aec',
    messagingSenderId: '825282016133',
    projectId: 'praynotify',
    authDomain: 'praynotify.firebaseapp.com',
    databaseURL: 'https://praynotify-default-rtdb.firebaseio.com',
    storageBucket: 'praynotify.firebasestorage.app',
    measurementId: 'G-WH454J3B68',
  );
}
